const clamp = (n, min = 0, max = 255) => Math.max(min, Math.min(max, Math.round(n)));
export const DEFAULT_STORE_THEME = { primary: '#f97316', primaryHover: '#c2410c', primaryLight: '#ffedd5', secondary: '#334155', accent: '#fdba74', background: '#fff7ed', surface: '#ffffff', textPrimary: '#111827', textSecondary: '#475569', border: '#fed7aa', sidebarBackground: '#1f2937', sidebarText: '#ffffff', buttonText: '#111827' };
export const hexToRgb = (hex) => { let clean = String(hex || '').replace('#', ''); if (/^[\da-f]{3}$/i.test(clean)) clean = clean.split('').map((value) => value + value).join(''); return /^[\da-f]{6}$/i.test(clean) ? [0, 2, 4].map((i) => parseInt(clean.slice(i, i + 2), 16)) : null; };
export const rgbToHex = (rgb) => `#${rgb.map((v) => clamp(v).toString(16).padStart(2, '0')).join('')}`;
export const relativeLuminance = (hex) => (hexToRgb(hex) || [0, 0, 0]).map((v) => { v /= 255; return v <= .03928 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4; }).reduce((sum, v, i) => sum + v * [.2126, .7152, .0722][i], 0);
export const contrastRatio = (a, b) => { const [hi, lo] = [relativeLuminance(a), relativeLuminance(b)].sort((x, y) => y - x); return (hi + .05) / (lo + .05); };
export const readableText = (background) => contrastRatio(background, '#fff') >= contrastRatio(background, '#111827') ? '#ffffff' : '#111827';
export const mixColors = (a, b, ratio) => { const left = hexToRgb(a) || hexToRgb(DEFAULT_STORE_THEME.primary); const right = hexToRgb(b) || hexToRgb('#fff'); return rgbToHex(left.map((v, i) => v + (right[i] - v) * ratio)); };
const saturation = ([r, g, b]) => (Math.max(r, g, b) - Math.min(r, g, b)) / 255;
const usable = (hex) => { const rgb = hexToRgb(hex); const lum = relativeLuminance(hex); return rgb && saturation(rgb) > .12 && lum > .035 && lum < .9; };
export function generateStoreTheme(primaryInput, secondaryInput) { const primary = usable(primaryInput) ? primaryInput : DEFAULT_STORE_THEME.primary; const secondary = usable(secondaryInput) ? secondaryInput : mixColors(primary, '#1f2937', .65); const sidebar = relativeLuminance(secondary) < .08 ? mixColors(secondary, '#ffffff', .12) : secondary; return { primary, primaryHover: mixColors(primary, '#111827', .22), primaryLight: mixColors(primary, '#ffffff', .84), secondary, accent: mixColors(primary, '#ffffff', .45), background: mixColors(primary, '#ffffff', .94), surface: '#ffffff', textPrimary: '#111827', textSecondary: '#475569', border: mixColors(primary, '#ffffff', .7), sidebarBackground: sidebar, sidebarText: readableText(sidebar), buttonText: readableText(primary) }; }
export async function extractLogoPalette(file) { const image = await createImageBitmap(file); const limit = 180; const scale = Math.min(1, limit / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); const ctx = canvas.getContext('2d', { willReadFrequently: true }); ctx.drawImage(image, 0, 0, canvas.width, canvas.height); image.close?.(); const counts = new Map(); const pixels = ctx.getImageData(0, 0, canvas.width, canvas.height).data; for (let i = 0; i < pixels.length; i += 4) { if (pixels[i + 3] < 80) continue; const rgb = [pixels[i], pixels[i + 1], pixels[i + 2]]; const key = rgbToHex(rgb.map((v) => Math.round(v / 24) * 24)); const lum = relativeLuminance(key); if ((lum > .94 || lum < .018) && saturation(rgb) < .18) continue; counts.set(key, (counts.get(key) || 0) + 1); } const all = [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([hex]) => hex); const candidates = all.filter(usable); const dominant = candidates[0] || DEFAULT_STORE_THEME.primary; return { dominant, vibrant: candidates.filter((hex) => saturation(hexToRgb(hex)) > .35).slice(0, 5), muted: candidates.filter((hex) => saturation(hexToRgb(hex)) <= .35).slice(0, 5), dark: candidates.filter((hex) => relativeLuminance(hex) < .22).slice(0, 5), light: candidates.filter((hex) => relativeLuminance(hex) >= .22).slice(0, 5), all: all.slice(0, 12) }; }
export const themeFromPalette = (palette, variation = 0) => { const options = [...new Set([...(palette?.vibrant || []), ...(palette?.light || []), palette?.dominant].filter(usable))]; const primary = options[variation % Math.max(1, options.length)] || DEFAULT_STORE_THEME.primary; const secondaryOptions = [...new Set([...(palette?.dark || []), ...(palette?.muted || []), ...options])].filter((hex) => hex !== primary); return generateStoreTheme(primary, secondaryOptions[(variation + 1) % Math.max(1, secondaryOptions.length)]); };
