import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabaseClient';
import { Edit2, Eye, Plus, ReceiptText, Settings2, Trash2, X } from 'lucide-react';

const blankGroup = { name: '', accounting_code: '', tax_profile_id: '', is_active: true };
const blankProfile = { name: '', dine_in_tax_rate_id: '', takeaway_tax_rate_id: '', delivery_tax_rate_id: '', default_tax_rate_id: '', is_active: true };

export default function TaxManagement({ store, showNotification, isArabic }) {
  const [groups, setGroups] = useState([]); const [profiles, setProfiles] = useState([]); const [rates, setRates] = useState([]); const [products, setProducts] = useState([]);
  const [groupEditor, setGroupEditor] = useState(null); const [profilesOpen, setProfilesOpen] = useState(false); const [profileEditor, setProfileEditor] = useState(null); const [saving, setSaving] = useState(false); const [reviewGroup, setReviewGroup] = useState(null);
  const t = (ar, en) => isArabic ? ar : en;
  const load = useCallback(async () => { if (!store?.id) return; try {
    const [g, p, r, productsResult] = await Promise.all([
      supabase.from('accounting_groups').select('*').eq('store_id', store.id).order('name'), supabase.from('tax_profiles').select('*').eq('store_id', store.id).order('name'), supabase.from('tax_rates').select('*').eq('store_id', store.id).order('rate'), supabase.from('products').select('id,name,accounting_group_id').eq('store_id', store.id).order('name')
    ]); if (g.error || p.error || r.error || productsResult.error) throw g.error || p.error || r.error || productsResult.error; setGroups(g.data || []); setProfiles(p.data || []); setRates(r.data || []); setProducts(productsResult.data || []);
  } catch (e) { console.error(e); showNotification(t('تعذر تحميل المجموعات المحاسبية', 'Unable to load accounting groups'), 'error'); } }, [store?.id, isArabic, showNotification]);
  useEffect(() => { load(); }, [load]);
  const profileById = useMemo(() => Object.fromEntries(profiles.map(p => [p.id, p])), [profiles]); const rateById = useMemo(() => Object.fromEntries(rates.map(r => [r.id, r])), [rates]);
  const countProducts = id => products.filter(p => p.accounting_group_id === id).length;
  // POS only sells dine-in and takeaway. Delivery rates are kept for ordering integrations
  // and must not prevent a restaurant from completing an in-store order.
  const groupConfigured = group => { const profile = profileById[group.tax_profile_id]; return Boolean(profile?.is_active && profile.dine_in_tax_rate_id && profile.takeaway_tax_rate_id); };
  const rateLabel = id => id ? `${rateById[id]?.name || '—'} (${Number(rateById[id]?.rate || 0)}%)` : t('غير محدد', 'Not set');
  const profileSummary = profile => profile ? `${profile.name} — ${t('صالة','Dine-in')} ${Number(rateById[profile.dine_in_tax_rate_id]?.rate ?? 0)}% · ${t('سفري','Takeaway')} ${Number(rateById[profile.takeaway_tax_rate_id]?.rate ?? 0)}%` : t('يحتاج إعداد الضريبة', 'Needs tax configuration');
  const save = async (fn, success) => { try { setSaving(true); const { error } = await fn(); if (error) throw error; showNotification(success, 'success'); await load(); } catch (e) { showNotification(e.message || t('فشل الحفظ', 'Save failed'), 'error'); } finally { setSaving(false); } };
  const saveGroup = e => { e.preventDefault(); const value = groupEditor; if (!value.name) return; save(() => value.id ? supabase.from('accounting_groups').update({ name:value.name.trim(), accounting_code:value.accounting_code.trim() || null, tax_profile_id:value.tax_profile_id || null, is_active:value.is_active }).eq('id', value.id) : supabase.from('accounting_groups').insert({ store_id:store.id, name:value.name.trim(), accounting_code:value.accounting_code.trim() || null, tax_profile_id:value.tax_profile_id || null, is_active:value.is_active, is_default:false }), t('تم حفظ المجموعة المحاسبية', 'Accounting group saved')); setGroupEditor(null); };
  const saveProfile = e => { e.preventDefault(); const value = profileEditor; if (!value.name) return; save(() => value.id ? supabase.from('tax_profiles').update({ ...value, id:undefined, store_id:undefined }).eq('id', value.id) : supabase.from('tax_profiles').insert({ ...value, store_id:store.id }), t('تم حفظ ملف الضريبة', 'Tax profile saved')); setProfileEditor(null); };
  const toggleGroup = group => save(() => supabase.from('accounting_groups').update({ is_active:!group.is_active }).eq('id',group.id), t('تم تحديث الحالة', 'Status updated'));
  const deleteGroup = group => { if (countProducts(group.id)) return showNotification(t('لا يمكن حذف مجموعة مرتبطة بمنتجات.', 'A group with products cannot be deleted.'), 'error'); if (confirm(t(`حذف مجموعة ${group.name}؟`, `Delete ${group.name}?`))) save(() => supabase.from('accounting_groups').delete().eq('id',group.id), t('تم حذف المجموعة', 'Group deleted')); };
  const selectClass = 'w-full mt-1 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 px-3 py-2.5 text-xs';
  const Modal = ({ children, close }) => <div className="fixed inset-0 z-[70] bg-slate-950/45 flex items-center justify-center p-4 backdrop-blur-sm"><div dir={isArabic?'rtl':'ltr'} className="max-w-lg w-full max-h-[90vh] overflow-y-auto rounded-3xl bg-white dark:bg-slate-800 shadow-2xl border border-slate-200 dark:border-slate-700"><div className="p-5 border-b flex justify-between"><b>{t('المجموعات المحاسبية', 'Accounting Groups')}</b><button onClick={close}><X className="w-5 h-5" /></button></div>{children}</div></div>;
  return <div dir={isArabic?'rtl':'ltr'} className="max-w-6xl mx-auto space-y-5">
    <div className="flex flex-col sm:flex-row justify-between gap-3 sm:items-center"><div><h2 className="text-xl font-black text-slate-800 dark:text-white">{t('المجموعات المحاسبية', 'Accounting Groups')}</h2><p className="text-xs text-slate-500 mt-1">{t('اربط المنتج بمجموعة، والمجموعة بملف الضريبة المناسب.', 'Assign a product to a group, then link that group to its tax profile.')}</p></div><div className="flex gap-2"><button onClick={()=>setProfilesOpen(true)} className="px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-bold flex gap-2"><Settings2 className="w-4 h-4" />{t('إدارة ملفات الضريبة', 'Manage Tax Profiles')}</button><button onClick={()=>setGroupEditor(blankGroup)} className="px-4 py-2.5 rounded-xl bg-amber-500 text-white text-xs font-bold flex gap-2"><Plus className="w-4 h-4" />{t('إنشاء مجموعة', 'Create Accounting Group')}</button></div></div>
    <div className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900 rounded-2xl px-4 py-3 text-xs text-amber-900 dark:text-amber-200">{t('المجموعات التي تحتاج إعداداً لا تمنع إدارة المنتجات، لكنها تمنع الدفع حتى ربط ملف ضريبة صالح.', 'Groups needing configuration do not block catalog work; they block checkout until a valid tax profile is linked.')}</div>
    <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900/50 text-slate-500"><tr><th className="p-4 text-start">{t('اسم المجموعة', 'Accounting Group')}</th><th className="p-4 text-start">{t('المعرّف المحاسبي', 'Accounting ID')}</th><th className="p-4 text-start">{t('ملف الضريبة', 'Tax Profile')}</th><th className="p-4 text-center">{t('المنتجات', 'Products')}</th><th className="p-4 text-center">{t('الحالة', 'Status')}</th><th className="p-4 text-end">{t('إجراءات', 'Actions')}</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{groups.map(group => { const configured=groupConfigured(group); return <tr key={group.id}><td className="p-4 font-bold">{group.name}</td><td className="p-4 text-slate-500">{group.accounting_code || '—'}</td><td className="p-4"><span className={configured?'text-emerald-600 font-bold':'text-amber-600 font-bold'}>{configured ? profileSummary(profileById[group.tax_profile_id]) : t('يحتاج إعداد الضريبة', 'Needs tax configuration')}</span></td><td className="p-4 text-center">{countProducts(group.id)}</td><td className="p-4 text-center"><span className={`px-2 py-1 rounded-full text-[10px] font-bold ${group.is_active?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{group.is_active?t('نشطة','Active'):t('موقفة','Inactive')}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button title={t('مراجعة المنتجات','Review products')} onClick={()=>setReviewGroup(group)} className="p-2 rounded-lg hover:bg-slate-100"><Eye className="w-4 h-4" /></button><button title={t('تعديل','Edit')} onClick={()=>setGroupEditor(group)} className="p-2 rounded-lg hover:bg-slate-100"><Edit2 className="w-4 h-4" /></button><button onClick={()=>toggleGroup(group)} className="text-[10px] font-bold text-amber-600">{group.is_active?t('إيقاف','Deactivate'):t('تفعيل','Activate')}</button><button title={t('حذف','Delete')} onClick={()=>deleteGroup(group)} disabled={Boolean(countProducts(group.id))} className="p-2 text-rose-500 disabled:opacity-30"><Trash2 className="w-4 h-4" /></button></div></td></tr>; })}{groups.length===0&&<tr><td colSpan="6" className="p-10 text-center text-slate-500">{t('لا توجد مجموعات محاسبية.', 'No accounting groups yet.')}</td></tr>}</tbody></table></div>
    {groupEditor&&<Modal close={()=>setGroupEditor(null)}><form onSubmit={saveGroup} className="p-5 space-y-4"><h3 className="font-black">{groupEditor.id?t('تعديل المجموعة المحاسبية','Edit Accounting Group'):t('إنشاء مجموعة محاسبية','Create Accounting Group')}</h3><label className="text-xs font-bold">{t('اسم المجموعة','Accounting Group Name')}<input required value={groupEditor.name} onChange={e=>setGroupEditor({...groupEditor,name:e.target.value})} className={selectClass}/></label><label className="text-xs font-bold">{t('المعرّف المحاسبي','Accounting ID')}<input value={groupEditor.accounting_code||''} onChange={e=>setGroupEditor({...groupEditor,accounting_code:e.target.value})} className={selectClass}/></label><label className="text-xs font-bold">{t('ملف الضريبة','Tax Profile')}<select value={groupEditor.tax_profile_id||''} onChange={e=>setGroupEditor({...groupEditor,tax_profile_id:e.target.value})} className={selectClass}><option value="">{t('يحتاج إعداد الضريبة','Needs tax configuration')}</option>{profiles.filter(p=>p.is_active).map(p=><option value={p.id} key={p.id}>{profileSummary(p)}</option>)}</select></label><label className="flex gap-2 text-xs"><input type="checkbox" checked={groupEditor.is_active} onChange={e=>setGroupEditor({...groupEditor,is_active:e.target.checked})}/>{t('نشطة','Active')}</label><button disabled={saving} className="w-full rounded-xl bg-amber-500 text-white font-bold text-xs py-3">{t('حفظ','Save')}</button></form></Modal>}
    {reviewGroup&&<Modal close={()=>setReviewGroup(null)}><div className="p-5"><h3 className="font-black mb-3">{reviewGroup.name}</h3>{products.filter(p=>p.accounting_group_id===reviewGroup.id).map(p=><p className="py-2 border-b text-xs" key={p.id}>{p.name}</p>) || <p>{t('لا توجد منتجات','No products')}</p>}</div></Modal>}
    {profilesOpen&&<Modal close={()=>setProfilesOpen(false)}><div className="p-5 space-y-3"><div className="flex justify-between items-center"><h3 className="font-black">{t('ملفات الضريبة المتقدمة','Advanced Tax Profiles')}</h3><button onClick={()=>setProfileEditor(blankProfile)} className="text-xs bg-amber-500 text-white rounded-xl px-3 py-2">{t('إضافة ملف','Add Profile')}</button></div>{profiles.map(p=><div className="border rounded-xl p-3 text-xs" key={p.id}><div className="flex justify-between"><b>{p.name}</b><button onClick={()=>setProfileEditor(p)} className="text-amber-600">{t('تعديل','Edit')}</button></div><p className="text-slate-500 mt-1">{t('محلي','Dine in')}: {rateLabel(p.dine_in_tax_rate_id)} · {t('سفري','Takeaway')}: {rateLabel(p.takeaway_tax_rate_id)} · {t('توصيل','Delivery')}: {rateLabel(p.delivery_tax_rate_id)}</p></div>)}</div></Modal>}
    {profileEditor&&<Modal close={()=>setProfileEditor(null)}><form onSubmit={saveProfile} className="p-5 space-y-3"><h3 className="font-black">{t('ملف ضريبة','Tax Profile')}</h3><input required value={profileEditor.name} onChange={e=>setProfileEditor({...profileEditor,name:e.target.value})} placeholder={t('اسم الملف','Profile name')} className={selectClass}/>{[['dine_in_tax_rate_id',t('محلي','Dine in')],['takeaway_tax_rate_id',t('سفري','Takeaway')],['delivery_tax_rate_id',t('توصيل','Delivery')],['default_tax_rate_id',t('افتراضي','Fallback')]].map(([key,label])=><label className="block text-xs font-bold" key={key}>{label}<select value={profileEditor[key]||''} onChange={e=>setProfileEditor({...profileEditor,[key]:e.target.value})} className={selectClass}><option value="">{t('غير محدد','Not set')}</option>{rates.filter(r=>r.is_active).map(r=><option value={r.id} key={r.id}>{r.name} ({Number(r.rate)}%)</option>)}</select></label>)}<button disabled={saving} className="w-full py-3 rounded-xl bg-amber-500 text-white font-bold text-xs">{t('حفظ','Save')}</button></form></Modal>}
  </div>;
}
